language: node_js
services:
  - redis-server
cache:
  directories:
    - node_modules
notifications:
  email: false
node_js:
  - '12'
deploy:
  skip_cleanup: true
  on:
    repo: iamolegga/nestjs-ratelimiter
    branch: master
  provider: npm
  email: iamolegga@gmail.com
  api_key:
    secure: Wojpoea0kxkVAlj7piP4e/6CKU6dYaoFZwe2N4mg3housrV9OwzgUDmnPTJwQyjsCv0ON6SZmAmX5mXbzZhBueGIWTfrH2JjTbmJ5VUVaIcCT3lGjrZJLcWm8X0M9UNsIpX34ZysnCJmmnxROwKetLmufOsTPDTq9DYo+3Fb8Yo4cI4b/RsXymcLaZcg2ZMI3TPuWb/J7Orc+sWE2uDiLVwX5gtIq9VlgwW9p8tt2isEQd+NrOawUKWa60wk4EnDBoaHK/H9jpjZmRzzF8kMjagtR7C0gzYCIoGxdU02lIyetHjQ2VaWzTyy5h08RAZCDWzDYu6ad5ao0DyU5ry5DXQnIM/5WOSYjgvUBcciPBplIN8RRE+VAcvjI4W0LYgZJ/6WqP8vIaYYTgqNFLN4XUMw7Ix6bPqlpRBqt/NEkvEH/2vb9pUYupdVRV5n/BWFw75Bkzd/IC5nA83IhB6is2YXxHe+9NWLBCrNigrAkaKffLrgE4PJ3mGE/AeltACCNaErRiWKje5ThGhEtyvnct7yNfmJvurTCC/WP7RPTKm1KlFMYMl+7gqP6OBY9ihaDr0aEiaK8pSs+ef1tk42KHdHbMusXGwRLQL5z69uJIavcBGQ1rx3Vn9sZqGcYNrC2HI2Xw6BCgEUp2RI8JFs0SPwYcPwzX4SoRVa6oevM2U=
script:
  - npm run build
  - npm run test
after_deploy:
  - npm run report
branches:
  except:
    - "/^v\\d+\\.\\d+\\.\\d+$/"
